branches:
  only:
    - "master"
gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
install:
  - 'travis_retry bundle install'
language:
  - ruby
rvm:
  - 2.3.7
  - 2.4.5
  - 2.5.3
script: 'bundle exec rake spec'
notifications:
  email: false
sudo: false
cache: bundler
